# Generated by Django 5.0.2 on 2024-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
